apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlflow
spec:
  selector:
    matchLabels:
      app: mlflow
  replicas: 1
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: "ghcr.io/mlflow/mlflow:latest"
          ports:
            - containerPort: 5000
          command: ["mlflow", "server"]
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: mlflow
spec:
  selector:
    app: mlflow
  ports:
    - name: mlflow
      protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 32000
  type: LoadBalancer
